sonar.projectKey=JoshnaChary_notes_application
sonar.organization=joshnachary
sonar.sources=lib
sonar.tests=test
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/generated/**,\
                 **/*.g.dart,\
                 **/*.freezed.dart,\
                 **/build/**,\
                 windows/**,\
                 linux/**,\
                 macos/**,\
                 ios/**,\
                 android/**
sonar.coverage.reportPath=./coverage/lcov.info

